"""A clearly-labelled synthetic scene, for smoke tests without any data.

Nothing here is a research output.  The scene exists so that the renderer,
storyboard and exporters can be exercised on a machine that has no IDSSE data,
and so that a reviewer can see the full visual language in one frame.
"""

from __future__ import annotations

import numpy as np

from ..scene import Scene, ScenePlayer

FPS = 25.0
DURATION_S = 9.0


def synthetic_scene(seed: int = 7) -> Scene:
    """A generated 1-1-1 scene. Never a research output; labelled in frame."""

    rng = np.random.default_rng(seed)
    n = int(DURATION_S * FPS)
    times = np.arange(n) / FPS - 6.0

    def lerp(a, b, t):
        return np.stack([np.interp(t, [0, 1], [a[0], b[0]]),
                         np.interp(t, [0, 1], [a[1], b[1]])], axis=1)

    progress = np.clip((times + 4.0) / 6.0, 0.0, 1.0)
    ease = progress * progress * (3 - 2 * progress)

    players: dict[str, ScenePlayer] = {}

    def add(pid, team, side, shirt, name, start, end, wobble=0.35, keeper=False):
        xy = lerp(start, end, ease)
        xy += rng.normal(0, wobble, size=xy.shape).cumsum(axis=0) * 0.06
        players[pid] = ScenePlayer(pid, team, side, shirt, name, xy,
                                   is_goalkeeper=keeper)

    add("SYN-A-07", "SYN-ATT", "attack", "7", "Runner", (14.0, -14.0), (36.0, -3.0))
    add("SYN-D-11", "SYN-DEF", "defend", "11", "Marker", (20.0, -9.0), (34.0, -1.0))
    add("SYN-A-34", "SYN-ATT", "attack", "34", "Beneficiary", (10.0, 12.0), (30.0, 13.0))
    add("SYN-A-09", "SYN-ATT", "attack", "9", "Carrier", (2.0, 2.0), (12.0, 6.0))
    add("SYN-D-01", "SYN-DEF", "defend", "1", "Keeper", (50.0, 0.0), (49.0, 1.0),
        wobble=0.05, keeper=True)
    add("SYN-A-01", "SYN-ATT", "attack", "1", "Keeper", (-50.0, 0.0), (-49.0, -1.0),
        wobble=0.05, keeper=True)
    for index in range(7):
        angle = index / 7 * 2 * np.pi
        add(f"SYN-D-{20 + index}", "SYN-DEF", "defend", str(20 + index), f"Def {index}",
            (26.0 + 12 * np.cos(angle), 10 * np.sin(angle)),
            (32.0 + 11 * np.cos(angle), 12 * np.sin(angle)))
    for index in range(6):
        angle = index / 6 * 2 * np.pi + 0.4
        add(f"SYN-A-{20 + index}", "SYN-ATT", "attack", str(20 + index), f"Att {index}",
            (6.0 + 14 * np.cos(angle), 14 * np.sin(angle)),
            (18.0 + 13 * np.cos(angle), 15 * np.sin(angle)))

    ball = players["SYN-A-09"].xy.copy()
    hand_off = int(0.65 * n)
    ball[hand_off:] = np.linspace(
        ball[hand_off], players["SYN-A-34"].xy[-1], n - hand_off
    )

    return Scene(
        scene_id="SYNTHETIC:smoke-test",
        source="synthetic",
        fps=FPS,
        times=times,
        players=players,
        ball_xy=ball,
        attacking_team_id="SYN-ATT",
        defending_team_id="SYN-DEF",
        attacking_direction=1,
        runner_ids=("SYN-A-07",),
        defender_ids=("SYN-D-11",),
        beneficiary_ids=("SYN-A-34",),
        carrier_ids=("SYN-A-09",),
        title="Synthetic smoke-test scene",
        subtitle="not real tracking · not a research output · renderer check only",
        attacking_team_name="Synthetic Attack",
        defending_team_name="Synthetic Defence",
        notes="Generated by demo_viz.sources.synthetic for renderer smoke tests.",
        frame_ids=np.arange(n),
        moments={"shot": 3.0},
        provenance={
            "adapter": "synthetic",
            "annotation_effect": "synthetic",
            "match_id": "SYNTHETIC",
            "period": 1,
            "source_fps": FPS,
            "warning": "All positions are generated. Never present as data.",
        },
    )
