#!/usr/bin/env python3
"""Export real solver artifacts for the browser, and nothing else.

    python -m demo_viz.web.export_solver --run ~/Research/offball_demo/mit_ssac2027_ref/results/exact_100 --states 3 6
    python -m demo_viz.web.export_solver --from-manifest

Writes ``demo_viz/web_data/solver/<key>.json``, lazy-loaded by the browser when
a visitor turns the Solver layer on. Each file carries the run's provenance --
repository, commit, artifact directory, state index, the solver's own policy
fingerprint and the run timestamp -- so any number on screen can be traced back
to the run that produced it.

WHAT THIS DOES NOT DO
---------------------
It does not run the solver, and it does not manufacture a state for a scene
that has none. A demo scene with no artifact simply has no file here, and the
browser reports *Not computed for this scene*. That is the only honest thing
to show: a trajectory generated by anything other than the solver is not a
solver result, however plausible it looks.

The exact_100 states are the solver's own declared 2v1 study states. They are
**not** Bundesliga scenes and are exported under a ``solver_reference`` kind so
the interface can never present them as match footage.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    __package__ = "demo_viz.web"

from ..core.submission import load as load_manifest  # noqa: E402
from ..solver import SolverState, load_state  # noqa: E402
from .export_data import WEB_DATA, slug  # noqa: E402

SOLVER_DIR = WEB_DATA / "solver"


def _commit_of(path: Path) -> str:
    """The reference repository's commit, read rather than assumed."""

    for parent in [path, *path.parents]:
        if (parent / ".git").exists():
            try:
                out = subprocess.run(
                    ["git", "-C", str(parent), "rev-parse", "--short", "HEAD"],
                    capture_output=True, text=True, timeout=20,
                )
                if out.returncode == 0:
                    return out.stdout.strip()
            except Exception:                              # pragma: no cover
                return "unknown"
    return "unknown"


def payload_for(state: SolverState, key: str, kind: str) -> dict:
    data = state.to_payload()
    data["key"] = key
    data["kind"] = kind
    data["label"] = (
        f"Solver reference · {state.name}" if kind == "solver_reference" else state.name
    )
    data["caveat"] = (
        "A declared 2v1 study state from the solver's own scenario set, not a "
        "tracked match scene."
        if kind == "solver_reference" else ""
    )
    return data


def export_state(run_dir: Path, index: int, out_dir: Path, *, kind: str,
                 key: str | None = None, commit: str | None = None) -> Path:
    commit = commit or _commit_of(run_dir)
    state = load_state(run_dir, index, commit=commit)
    key = key or f"solver_{run_dir.name}_{index:03d}"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{slug(key)}.json"
    path.write_text(json.dumps(payload_for(state, key, kind), separators=(",", ":")))
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run", type=Path, default=None,
                        help="a solver run directory (holds manifest.json)")
    parser.add_argument("--states", type=int, nargs="*", default=None)
    parser.add_argument("--from-manifest", action="store_true",
                        help="export whatever submission_scenes.json points at")
    parser.add_argument("--out", type=Path, default=SOLVER_DIR)
    args = parser.parse_args(argv)

    written: list[Path] = []

    if args.from_manifest:
        entries = load_manifest()
        if entries is None:
            print("no submission manifest; nothing to export", file=sys.stderr)
        else:
            for entry in entries:
                if not entry.solver_artifact:
                    continue
                run, _, index = entry.solver_artifact.partition("#")
                run_path = Path(run).expanduser()
                if not index.isdigit() or not run_path.exists():
                    print(f"!! {entry.scene_id}: unusable solver_artifact "
                          f"{entry.solver_artifact}", file=sys.stderr)
                    continue
                written.append(export_state(run_path, int(index), args.out,
                                            kind=entry.kind, key=entry.scene_id))
                print(f"wrote {written[-1].name}  <- {entry.solver_artifact}")

    if args.run:
        run_path = args.run.expanduser()
        for index in (args.states or [0]):
            written.append(export_state(run_path, index, args.out,
                                        kind="solver_reference"))
            print(f"wrote {written[-1].name}  <- {run_path.name}#{index}")

    if not written:
        print("nothing exported", file=sys.stderr)
        return 1
    total = sum(p.stat().st_size for p in written)
    print(f"\n{len(written)} solver files, {total / 1024:.0f} KB total "
          f"(lazy-loaded, one at a time) -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
