#!/usr/bin/env python3
"""Build the curated showcase metadata from the local source.

    python -m demo_viz.ingest_showcase                  # write the tracked file
    python -m demo_viz.ingest_showcase --report         # print the mapping table
    python -m demo_viz.ingest_showcase --check          # fail if the file is stale

Reads ``local_inputs/dilemma_showcase.html``, which is local-only and carries
embedded tracking, and writes ``demo_viz/data/submission_showcase.json``, which
carries **curation metadata and mappings only**. No trajectory crosses that
line: a showcase scene is played from the repository scene it maps to, or it is
not played at all.

The output is committed; the input is not. Re-run this when the curated set
changes, and `--check` in CI-ish contexts to notice drift.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    __package__ = "demo_viz"

from .core.showcase_ingest import (  # noqa: E402
    DEFAULT_SOURCE,
    map_all,
    read_showcase,
    repository_scenes,
)

OUT = Path(__file__).resolve().parent / "data" / "submission_showcase.json"

#: Trajectories are the one thing that must never come from the local source.
FORBIDDEN_KEYS = ("t", "ball", "xy", "players", "tracks")

#: The case study the demo opens on.
#:
#: S05 is the paper's Figure 1 and Figure 2 scene, and the one whose solved
#: data tells the whole story in one place: a defensive dilemma at every one of
#: its three moments, a mixed defender policy of 57/43 at 0.6 s, the through
#: ball the equilibrium plays 74% of the time, and a static reading of the same
#: choice overstating its value by 40.1% once the defender may answer.
#:
#: This is a curation decision, so it lives here rather than in the generated
#: file: `order` is read by the selector's sort, the ingest writes it, and
#: `--check` still proves the committed file is what this code produces. It
#: does **not** set `featured` -- no final ten has been chosen, so the default
#: filter stays "all" and every curated scene stays in the list.
LEAD_SCENE = "S05"


def build(source: Path | None = None) -> dict:
    entries = map_all(read_showcase(source), repository_scenes())
    records = []
    for entry in sorted(entries, key=lambda e: e.showcase_id):
        solver_status = "unresolved" if entry.provenance == "solver" else "unavailable"
        records.append({
            "showcase_id": entry.showcase_id,
            "scene_id": entry.scene_id,
            "featured": False,
            "order": 1 if entry.showcase_id == LEAD_SCENE else None,
            "provenance": entry.provenance,
            "review": {
                "reviewers": [
                    {
                        "name": r.get("name", ""),
                        "rating": int(r["rating"]) if str(r.get("rating", "")).isdigit() else None,
                        "offball": r.get("offball", ""),
                        "note": r.get("note", ""),
                    }
                    for r in entry.raters
                ],
                "agreement_label": entry.agreement_label,
            },
            "roles": {key: list(value) for key, value in entry.roles.items()},
            "role_labels": entry.role_names,
            "match": entry.match,
            "half": entry.half,
            "event": entry.event,
            "goal": entry.goal,
            "timing": entry.zero,
            "source_kind": entry.kind,
            "annotation": entry.annotation,
            "solver": {
                "scenario_type": entry.scenario_type,
                "artifact": None,
                "status": solver_status,
                "split_metrics": entry.split,
            },
            "mapping": {
                "status": entry.mapping_status,
                "evidence": entry.mapping_evidence,
                "candidates": list(entry.candidates),
            },
        })
    return {
        "_comment": [
            "Curation metadata for the submission showcase. Generated by",
            "python -m demo_viz.ingest_showcase from a local-only source that is",
            "not committed. Contains no player or ball trajectories: a scene is",
            "played from the repository scene_id it maps to, or not at all.",
            "featured/order are the only fields to edit when the final ten are",
            "chosen; no code change is needed. order=1 on the lead scene comes",
            "from ingest_showcase.LEAD_SCENE, not from a hand edit.",
        ],
        "scenes": records,
    }


def report(payload: dict) -> str:
    rows = ["  id   prov    scen  rating  mapping     scene_id",
            "  " + "-" * 74]
    for scene in payload["scenes"]:
        rows.append(
            f"  {scene['showcase_id']:4} {scene['provenance']:7} "
            f"{str(scene['solver']['scenario_type'] or '-'):5} "
            f"{scene['review']['agreement_label']:7} "
            f"{scene['mapping']['status']:11} {scene['scene_id'] or '-'}"
        )
    return "\n".join(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--report", action="store_true")
    parser.add_argument("--check", action="store_true",
                        help="compare against the committed file and fail on drift")
    args = parser.parse_args(argv)

    source = args.source or DEFAULT_SOURCE
    if not source.exists():
        print(f"!! showcase source not found: {source}", file=sys.stderr)
        print("   it is local-only and deliberately not committed", file=sys.stderr)
        return 2

    payload = build(source)
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"

    # belt and braces: the output must not carry a trajectory
    flat = json.dumps(payload)
    for key in FORBIDDEN_KEYS:
        if f'"{key}":' in flat:
            print(f"!! refusing to write: output contains '{key}'", file=sys.stderr)
            return 1

    if args.check:
        if not args.out.exists():
            print(f"!! {args.out} is missing", file=sys.stderr)
            return 1
        if args.out.read_text() != text:
            print(f"!! {args.out} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{args.out.name} is up to date")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    counts: dict[str, int] = {}
    for scene in payload["scenes"]:
        counts[scene["mapping"]["status"]] = counts.get(scene["mapping"]["status"], 0) + 1
    print(f"wrote {args.out}  ({len(payload['scenes'])} scenes, "
          f"{args.out.stat().st_size / 1024:.0f} KB)")
    print("  " + ", ".join(f"{k}: {v}" for k, v in sorted(counts.items())))
    if args.report:
        print()
        print(report(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
