"""Self-contained meeting gallery for the local off-ball game project."""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence


def build_meeting_gallery_payload(
    prototype: Mapping[str, object],
    observed_scenes: Sequence[Mapping[str, object]],
) -> dict[str, object]:
    """Attach one counterfactual prototype to eight unique observed scenes.

    The prototype shares a source frame with one observed scene and is exposed
    as an alternate view inside that scene, rather than as a ninth item.
    """

    if len(observed_scenes) != 8:
        raise ValueError(
            "The meeting gallery requires exactly eight confirmed observed scenes; "
            f"received {len(observed_scenes)}."
        )
    confirmed: list[dict[str, object]] = []
    for scene in observed_scenes:
        review = scene.get("core_review")
        if not isinstance(review, Mapping) or review.get("core_decision") != "include":
            raise ValueError("Every observed gallery scene must be human-confirmed.")
        confirmed.append(dict(scene))
    return {
        "schema_version": "meeting-scene-gallery-v0.1",
        "prototype": dict(prototype),
        "observed": confirmed,
        "scene_count": len(confirmed),
    }


_HTML = r"""<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Off-ball local game · 8-scene meeting gallery</title>
<style>:root{--bg:#071321;--panel:#101f32;--panel2:#16283e;--line:#324a65;--text:#f3f7ff;--muted:#afbdd0;--attack:#ff6d59;--defend:#438dff;--gold:#ffd052;--cyan:#45e0d0;--pink:#ff51c7;--violet:#c58cff;--orange:#ff9c43;--green:#65dda0}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,Pretendard,system-ui,sans-serif}main{max-width:1800px;margin:auto;padding:20px}h1,h2,h3{margin:0 0 8px}p{color:var(--muted);line-height:1.48}.notice{background:#192a42;border-left:4px solid var(--gold);border-radius:7px;padding:11px 14px;margin:10px 0 14px}.toolbar,.controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:10px 0}button,select{font:inherit;color:var(--text);background:#192b43;border:1px solid #4a6483;border-radius:8px;padding:9px 11px;cursor:pointer}select{min-width:520px}button.active{border-color:var(--gold);color:var(--gold);background:#2a2940}.count{font-weight:800;color:var(--gold);font-variant-numeric:tabular-nums}.layout{display:grid;grid-template-columns:minmax(760px,1fr) 500px;gap:15px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:14px}.pitch{width:100%;display:block;background:#17743a;border-radius:9px}.scrub{width:100%;padding:0}.time{font-variant-numeric:tabular-nums}.grow{flex:1}.badge{display:inline-block;border-radius:99px;padding:5px 10px;font-size:.76rem;font-weight:850;letter-spacing:.04em}.prototype-badge{background:#49351b;color:#ffd477}.observed-badge{background:#163e3c;color:#6aeee2}.legend{display:flex;gap:13px;flex-wrap:wrap;color:#c9d5e4;font-size:.82rem;margin-top:9px}.sw{display:inline-block;width:18px;border-top:4px solid;margin-right:5px}.dot{display:inline-block;width:11px;height:11px;border-radius:50%;margin-right:5px}.box{background:var(--panel2);border:1px solid #2d4561;border-radius:9px;padding:11px;margin:9px 0}.box strong{color:#f8fbff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{background:#13253a;border-radius:8px;padding:10px}.metric span{display:block;color:var(--muted);font-size:.75rem;margin-bottom:4px}.metric strong{font-size:.96rem}.mode-controls,.defender-controls{display:flex;gap:7px;flex-wrap:wrap}.section-label{width:100%;color:#cfdaea;font-size:.8rem;font-weight:800;margin-top:3px}.warning{color:#ffd477}.observed-note{color:#6aeee2}.hidden{display:none}.duplicate{font-size:.78rem;color:#f0c879}.tip{font-size:.82rem}.identity{font-weight:800}.prototype-info,.observed-info{display:grid;gap:3px}@media(max-width:1200px){.layout{grid-template-columns:1fr}select{min-width:280px;max-width:100%}}</style></head><body><main>
<h1>Off-ball local game · 8-scene meeting gallery</h1><p class="notice"><b>고유한 observed 장면 8개다.</b> Klaus–Kownacki 장면에서는 같은 원본 안에서 <b>실제 움직임 ↔ 기존 dynamic prototype</b>을 전환할 수 있다. 따라서 원본 장면을 중복해서 세지 않는다.</p>
<div class="toolbar"><button class="previous">← 이전</button><button class="next">다음 →</button><select class="scene-select"></select><button class="play">▶ 재생</button><div class="source-controls hidden"><button data-source="observed" class="active">실제 움직임</button><button data-source="prototype">Dynamic prototype</button></div><span class="count"></span></div>
<div class="layout"><section class="panel"><div class="controls"><span class="kind-badge badge"></span><h2 class="title"></h2><span class="grow"></span><span class="time"></span></div><p class="subtitle"></p><svg class="pitch" viewBox="0 0 105 68"><rect width="105" height="68" fill="#17743a" stroke="white" stroke-width=".32"/><line x1="52.5" x2="52.5" y1="0" y2="68" stroke="white" stroke-width=".25"/><circle cx="52.5" cy="34" r="9.15" fill="none" stroke="white" stroke-width=".25"/><rect x="0" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><rect x="88.5" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><path d="M43 3 L61 3 M58 1 L61 3 L58 5" stroke="#ffd052" stroke-width=".65" fill="none"/><text x="43" y="7" fill="#ffe49b" font-size="1.5">공격 방향</text><g class="static"></g><g class="moving"></g></svg><input class="scrub" type="range" min="0" value="0" step="1"><div class="legend"></div><p class="tip"></p></section>
<aside class="panel"><div class="dynamic-controls"><div class="defender-controls"><span class="section-label">누가 반응하는가?</span></div><div class="mode-controls"><span class="section-label">무엇을 억제하는가?</span></div></div><div class="details"></div></aside></div>
</main><script id="payload" type="application/json">__DATA__</script><script>
const P=JSON.parse(document.getElementById('payload').textContent),items=P.observed,params=new URLSearchParams(location.search);let si=Math.max(0,Math.min(items.length-1,Number(params.get('scene')||1)-1)),fi=0,bi=0,modeKey='dynamic_compromise',sourceView=params.get('view')==='prototype'?'prototype':'observed',playing=false,timer=null;const q=x=>document.querySelector(x),px=(d,x)=>52.5+d*x,py=y=>34-y,point=(d,x,y)=>[d*x,y],hasPrototype=s=>s.match_id===P.prototype.match_id&&s.onset_frame_id===P.prototype.onset_frame_id&&s.runner_id===P.prototype.runner_id;
function escapeHtml(x){return String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function interp(path,t){let p=[...path].sort((a,b)=>a[0]-b[0]);if(t<=p[0][0])return p[0].slice(1);if(t>=p[p.length-1][0])return p[p.length-1].slice(1);let j=p.findIndex(x=>x[0]>=t),a=p[j-1],b=p[j],f=(t-a[0])/(b[0]-a[0]);return[a[1]+f*(b[1]-a[1]),a[2]+f*(b[2]-a[2])]}
function poly(d,path,color,dash='',width=.5,opacity=.96){return`<polyline points="${path.map(p=>`${px(d,p[1])},${py(p[2])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}" stroke-dasharray="${dash}" opacity="${opacity}"/>`}
function stop(){playing=false;clearInterval(timer);q('.play').textContent='▶ 재생'}
const select=q('.scene-select');items.forEach((s,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`${i+1}/${items.length} · ${s.runner_name} / ${s.carrier_name} · frame ${s.onset_frame_id}${hasPrototype(s)?' · actual/dynamic':''}`;select.appendChild(o)});
function currentFrames(){return sourceView==='prototype'&&hasPrototype(items[si])?P.prototype.background_frames:items[si].frames}
function renderScene(){stop();fi=0;select.value=si;q('.count').textContent=`${si+1} / ${items.length}`;let s=items[si],available=hasPrototype(s);if(!available)sourceView='observed';q('.source-controls').classList.toggle('hidden',!available);q('.source-controls').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.source===sourceView));q('.dynamic-controls').classList.toggle('hidden',sourceView!=='prototype');if(sourceView==='prototype')renderPrototypeShell(P.prototype);else renderObservedShell(s);let frames=currentFrames();q('.scrub').max=frames.length-1;let onsetIndex=frames.findIndex(f=>(f.time_s??f.relative_time_s)>=0);fi=Math.max(0,onsetIndex);renderFrame()}
function renderPrototypeShell(s){q('.kind-badge').className='kind-badge badge prototype-badge';q('.kind-badge').textContent='COUNTERFACTUAL PROTOTYPE';q('.title').textContent=`${s.runner_name} → defender → ${s.ball_owner_name}`;q('.subtitle').innerHTML=`${escapeHtml(s.match_label)} · onset frame ${s.onset_frame_id} · horizon ${s.horizon_seconds.toFixed(1)}초 <span class="duplicate">(이 장면의 dynamic view)</span>`;q('.defender-controls').innerHTML='<span class="section-label">누가 반응하는가?</span>'+s.branches.map((b,i)=>`<button data-bi="${i}" class="${i===bi?'active':''}">${escapeHtml(b.defender_name)}</button>`).join('');q('.defender-controls').querySelectorAll('button').forEach(x=>x.onclick=()=>{bi=Number(x.dataset.bi);renderPrototypeShell(s);renderFrame()});let allowed=[['actual','실제 수비'],['dynamic_runner','Runner 억제'],['dynamic_carry','파생 옵션 억제'],['dynamic_compromise','Compromise']];q('.mode-controls').innerHTML='<span class="section-label">무엇을 억제하는가?</span>'+allowed.map(([k,l])=>`<button data-mode="${k}" class="${k===modeKey?'active':''}">${l}</button>`).join('');q('.mode-controls').querySelectorAll('button').forEach(x=>x.onclick=()=>{modeKey=x.dataset.mode;renderPrototypeShell(s);renderFrame()});let b=s.branches[bi],m=b.modes.find(x=>x.key===modeKey);q('.legend').innerHTML='<span><i class="sw" style="border-color:var(--pink)"></i>Klaus 후보</span><span><i class="sw" style="border-color:var(--violet)"></i>Kownacki carry 후보</span><span><i class="sw" style="border-color:white;border-top-style:dashed"></i>실제 수비</span><span><i class="sw" style="border-color:var(--cyan)"></i>선택 수비</span>';q('.tip').textContent='분홍·보라는 실제 공격 궤적이 아니라 기존 prototype에서 만든 두 공격 옵션이다. 수비 목적 버튼을 바꾸며 청록색 경로가 어떻게 달라지는지 본다.';q('.details').innerHTML=`<span class="badge prototype-badge">OLD MECHANISM DEMO</span><div class="box prototype-info"><strong>질문</strong><span>Klaus의 직접 위협을 막을 것인가, Kownacki의 전진 공간을 막을 것인가?</span></div><div class="grid"><div class="metric"><span>선택 수비수</span><strong>${escapeHtml(b.defender_name)}</strong></div><div class="metric"><span>현재 수비 목적</span><strong>${escapeHtml(m.label)}</strong></div><div class="metric"><span>Klaus geometry cost</span><strong>${Number(m.option_costs[0]).toFixed(2)} m</strong></div><div class="metric"><span>Kownacki geometry cost</span><strong>${Number(m.option_costs[1]).toFixed(2)} m</strong></div></div><div class="box"><strong>이 장면에서 볼 것</strong><p>① 반응 수비수를 Elvedi/Guwara로 바꿨을 때 결과가 달라지는가?<br>② Runner 억제와 파생 옵션 억제가 서로 다른 경로를 만드는가?<br>③ Compromise가 축구적으로 납득 가능한 중간 대응인가?</p></div><p class="warning"><b>주의:</b> 여기서 파생 옵션은 Kownacki carry로 고정한 초기 prototype이다. 최종 beneficiary 선정이나 완성된 위협 가치 함수의 결과가 아니다.</p>`}
function renderObservedShell(s){let r=s.core_review;q('.kind-badge').className='kind-badge badge observed-badge';q('.kind-badge').textContent='HUMAN-CONFIRMED OBSERVED';q('.title').textContent=`Runner ${s.runner_name} · Carrier ${s.carrier_name}`;q('.subtitle').textContent=`${s.match_label} · onset frame ${s.onset_frame_id} · 슈팅 ${s.seconds_before_shot.toFixed(1)}초 전`;q('.legend').innerHTML='<span><i class="dot" style="background:var(--gold)"></i>runner 궤적</span><span><i class="dot" style="background:var(--attack)"></i>공격팀</span><span><i class="dot" style="background:var(--defend)"></i>수비팀</span><span><i class="dot" style="background:#111;border:1px solid white"></i>공</span>';q('.tip').textContent='실제 움직임만 재생한다. 금색 테두리가 runner이고, t=0이 검출한 off-ball run onset이다.';q('.details').innerHTML=`<span class="badge observed-badge">ACTUAL MOTION</span><div class="box observed-info"><span>Runner <strong>${escapeHtml(s.runner_name)}</strong></span><span>Ball carrier <strong>${escapeHtml(s.carrier_name)}</strong></span><span>검출 근거 <strong>${escapeHtml((s.onset_labels||[]).join(' + '))}</strong></span></div><div class="box"><strong>네가 확인한 주 반응 수비</strong><p class="observed-note">${escapeHtml(r.primary_defender)}</p></div><div class="box"><strong>네가 확인한 파생 옵션</strong><p class="observed-note">${escapeHtml(r.derived_option)}</p></div><div class="grid"><div class="metric"><span>onset speed</span><strong>${s.onset_speed_mps.toFixed(2)} m/s</strong></div><div class="metric"><span>pre → post speed</span><strong>${s.pre_speed_mps.toFixed(2)} → ${s.post_speed_mps.toFixed(2)}</strong></div><div class="metric"><span>실제 슈팅까지</span><strong>${s.seconds_before_shot.toFixed(2)} s</strong></div><div class="metric"><span>Human core check</span><strong>include · yes/yes/yes</strong></div></div><p class="warning">이 8개에는 가상 수비·위협 점수를 아직 덧붙이지 않았다. 장면 구조를 확정한 observed development set이다.</p>`}
function renderFrame(){if(sourceView==='prototype'&&hasPrototype(items[si]))drawPrototype(P.prototype);else drawObserved(items[si]);q('.scrub').value=fi}
function drawPrototype(s){let f=s.background_frames[fi],t=f.time_s,d=s.attacking_direction,b=s.branches[bi],m=b.modes.find(x=>x.key===modeKey),actual=b.modes.find(x=>x.key==='actual'),runner=interp(b.options[0].path_txy,Math.max(0,t)),carry=interp(b.options[1].path_txy,Math.max(0,t)),defender=interp(m.response.path_txy,Math.max(0,t)),actualD=interp(actual.response.path_txy,Math.max(0,t)),hidden=[s.runner_id,s.ball_owner_id,b.defender_id];q('.static').innerHTML=poly(d,b.options[0].path_txy,'#ff51c7','',.62)+poly(d,b.options[1].path_txy,'#c58cff','',.65)+poly(d,actual.response.path_txy,'white','1 .55',.4,.8)+(modeKey==='actual'?'':poly(d,m.response.path_txy,'#45e0d0','',.68));let html=f.players.filter(p=>!hidden.includes(p[0])).map(p=>`<circle cx="${px(d,p[2])}" cy="${py(p[3])}" r=".67" fill="${p[1]===s.attacking_team_id?'#ff6d59':'#438dff'}" stroke="white" stroke-width=".13"><title>${escapeHtml(s.names[p[0]]||p[0])}</title></circle>`).join('');html+=`<circle cx="${px(d,runner[0])}" cy="${py(runner[1])}" r="1.0" fill="#ff51c7" stroke="white" stroke-width=".2"><title>${escapeHtml(s.runner_name)} candidate</title></circle><circle cx="${px(d,carry[0])}" cy="${py(carry[1])}" r="1.0" fill="#c58cff" stroke="white" stroke-width=".2"><title>${escapeHtml(s.ball_owner_name)} carry candidate</title></circle><circle cx="${px(d,carry[0])}" cy="${py(carry[1])}" r=".31" fill="#111" stroke="white" stroke-width=".1"/>`;html+=`<circle cx="${px(d,actualD[0])}" cy="${py(actualD[1])}" r="1.12" fill="none" stroke="white" stroke-width=".3"><title>actual ${escapeHtml(b.defender_name)}</title></circle>`;if(modeKey!=='actual')html+=`<circle cx="${px(d,defender[0])}" cy="${py(defender[1])}" r=".91" fill="#438dff" stroke="#45e0d0" stroke-width=".42"><title>counterfactual ${escapeHtml(b.defender_name)}</title></circle>`;q('.moving').innerHTML=html;q('.time').textContent=`t=${t>=0?'+':''}${t.toFixed(2)}초`}
function drawObserved(s){let f=s.frames[fi],d=s.attacking_direction,trail=s.frames.slice(0,fi+1).map(x=>x.players.find(p=>p[0]===s.runner_id)).filter(Boolean);q('.static').innerHTML=trail.length>1?`<polyline points="${trail.map(p=>`${px(d,p[2])},${py(p[3])}`).join(' ')}" fill="none" stroke="#ffd052" stroke-width=".52"/>`:'';let html=f.players.map(p=>{let attack=p[1]===s.team_id,runner=p[0]===s.runner_id,carrier=p[0]===s.carrier_id;return`<circle cx="${px(d,p[2])}" cy="${py(p[3])}" r="${runner ? 1.04 : .7}" fill="${attack ? '#ff6d59' : '#438dff'}" stroke="${runner ? '#ffd052' : carrier ? 'white' : 'white'}" stroke-width="${runner ? .5 : carrier ? .43 : .14}"><title>${escapeHtml(p[4])}</title></circle>`}).join('');if(f.ball){html+=`<circle cx="${px(d,f.ball[0])}" cy="${py(f.ball[1])}" r=".4" fill="#111" stroke="white" stroke-width=".16"/>`}q('.moving').innerHTML=html;q('.time').textContent=`t=${f.relative_time_s>=0?'+':''}${f.relative_time_s.toFixed(2)}초`}
q('.previous').onclick=()=>{si=(si-1+items.length)%items.length;sourceView='observed';renderScene()};q('.next').onclick=()=>{si=(si+1)%items.length;sourceView='observed';renderScene()};select.onchange=()=>{si=Number(select.value);sourceView='observed';renderScene()};q('.source-controls').querySelectorAll('button').forEach(x=>x.onclick=()=>{sourceView=x.dataset.source;renderScene()});q('.scrub').oninput=()=>{fi=Number(q('.scrub').value);renderFrame()};q('.play').onclick=()=>{playing=!playing;q('.play').textContent=playing?'❚❚ 일시정지':'▶ 재생';if(playing)timer=setInterval(()=>{let frames=currentFrames();fi=fi>=frames.length-1?Math.max(0,frames.findIndex(f=>(f.time_s??f.relative_time_s)>=0)):fi+1;renderFrame()},70);else clearInterval(timer)};renderScene();if(params.get('autoplay')==='1')q('.play').click();
</script></body></html>"""


def render_meeting_scene_gallery(payload: Mapping[str, object]) -> str:
    """Render the combined gallery as one self-contained HTML document."""

    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace(
        "</", "<\\/"
    )
    return _HTML.replace("__DATA__", data)
