"""Interactive human audit for shot-anchored attacking-phase sampling."""

from __future__ import annotations

import json
from typing import Sequence


def render_shot_context_audit(scenes: Sequence[dict[str, object]]) -> str:
    data = json.dumps(list(scenes), ensure_ascii=False, separators=(",", ":")).replace(
        "</", "<\\/"
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Shot-context attacking phase audit</title>
<style>
:root{{--bg:#0b1422;--panel:#111e31;--line:#344965;--muted:#aebbd0;--text:#f4f7fc;--attack:#ff6b55;--defend:#438cff;--gold:#ffc84a;--cyan:#5fe4ee}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}}main{{max-width:1500px;margin:auto;padding:24px}}h1{{margin:0 0 8px;font-size:32px}}p{{color:var(--muted);line-height:1.55}}.note{{background:#18253a;border-left:4px solid var(--gold);padding:11px 14px;border-radius:5px}}.toolbar,.controls,.review{{display:flex;gap:10px;align-items:center;flex-wrap:wrap}}button,select,input{{font:inherit;color:var(--text);background:#17253b;border:1px solid #486080;border-radius:8px;padding:9px 11px}}button{{cursor:pointer}}.toolbar select.scene{{min-width:410px}}.layout{{display:grid;grid-template-columns:minmax(720px,1fr) 390px;gap:16px;margin-top:16px}}.panel{{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:15px}}svg.pitch{{width:100%;display:block;background:#17723a;border-radius:8px}}input[type=range]{{width:100%;padding:0}}.time{{margin-left:auto;font-variant-numeric:tabular-nums}}.details,.metrics{{line-height:1.7;color:#c8d3e3}}.metrics strong{{color:#fff}}.legend{{display:grid;grid-template-columns:auto 1fr;gap:7px 9px;color:#c6d2e2;margin:13px 0}}.dot{{width:13px;height:13px;border-radius:50%;margin-top:5px}}.review{{align-items:flex-start;margin-top:14px}}.review label{{display:grid;gap:5px;color:#cbd5e3}}.review input{{flex:1;min-width:260px}}.status{{color:var(--cyan)}}.window-explanation{{padding:10px;background:#0e1929;border-radius:8px;color:#b8c6d9}}@media(max-width:1050px){{.layout{{grid-template-columns:1fr}}.toolbar select.scene{{min-width:280px;max-width:100%}}}}
</style></head><body><main>
<h1>Shot-context attacking phase · v0.1</h1>
<p class="note"><strong>The shot is only an anchor for finding scenes.</strong> It does not imply that an earlier off-ball run created this shot. This page only reviews which backtracking start point best shows a “genuine attacking phase”.</p>
<div class="toolbar"><button class="previous">← Previous</button><button class="next">Next →</button><select class="scene"></select><button class="export">Save review CSV</button><span class="status"></span></div>
<div class="layout"><section class="panel"><h2 class="title"></h2><p class="details"></p><svg class="pitch" viewBox="0 0 105 68" role="img" aria-label="Shot-ending attacking phase animation"><rect width="105" height="68" fill="#17723a" stroke="white" stroke-width=".35"/><line x1="52.5" y1="0" x2="52.5" y2="68" stroke="white" stroke-width=".25"/><circle cx="52.5" cy="34" r="9.15" fill="none" stroke="white" stroke-width=".25"/><rect x="0" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><rect x="88.5" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><path d="M43 3 L61 3 M58 1 L61 3 L58 5" stroke="#ffc84a" stroke-width=".65" fill="none"/><text x="43" y="7" fill="#ffe49b" font-size="1.5">Attacking direction</text><g class="ball-trail"></g><g class="objects"></g></svg><div class="controls"><label>Start point <select class="window"></select></label><button class="play">▶ Play</button><span class="time"></span></div><input class="slider" type="range" min="0" value="0" step="1"></section>
<aside class="panel"><h3>What to look for in this scene</h3><div class="window-explanation">Does the stretch from the selected start point to the shot look like one attacking phase? Does it start too early, or only after an important 2v1 has already happened?</div><div class="legend"><span class="dot" style="background:var(--attack)"></span><span>Shooting team</span><span class="dot" style="background:var(--defend)"></span><span>Defending team</span><span class="dot" style="background:var(--gold)"></span><span>Yellow ring = actual shooter</span><span class="dot" style="background:#111;border:2px solid white"></span><span>Ball · cyan trail = recent ball path</span></div><p class="metrics"></p><div class="review"><label>① Is this a valid attacking phase?<select class="phase-review"><option value="unreviewed">Unreviewed</option><option value="valid">Valid</option><option value="too_broad">Too broad</option><option value="too_late">Starts too late</option><option value="not_attack_context">Not an attacking phase</option><option value="ambiguous">Ambiguous</option></select></label><label>② Best start point<select class="start-review"><option value="unreviewed">Unreviewed</option><option value="window_10">10 s before</option><option value="window_15">15 s before</option><option value="window_30">30 s before</option><option value="window_60">60 s before</option><option value="possession">Estimated possession start</option><option value="attacking_half">Last entry into the opponent half</option></select></label><input class="review-note" placeholder="Note why the boundary looks wrong, or any 2v1 that stands out"></div></aside></div>
</main><script id="payload" type="application/json">{data}</script><script>
const scenes=JSON.parse(document.getElementById('payload').textContent),q=s=>document.querySelector(s),storage='shot-context-v0.1-reviews';let sceneIndex=0,visibleFrames=[],frameIndex=0,playing=false,timer=null,reviews={{}};try{{reviews=JSON.parse(localStorage.getItem(storage)||'{{}}')}}catch(e){{}}
const key=s=>`${{s.match_id}}:${{s.shot_frame_id}}:${{s.event_id}}`,px=x=>x+52.5,py=y=>34-y,sceneSelect=q('.scene'),windowSelect=q('.window');
scenes.forEach((s,i)=>{{const o=document.createElement('option');o.value=i;o.textContent=`${{i+1}}. ${{s.match_id.replace('DFL-MAT-','')}} · shot frame ${{s.shot_frame_id}} · ${{s.shooter_name}}`;sceneSelect.appendChild(o)}});
function normalizedPoint(scene,x,y){{return [scene.attacking_direction*x,scene.attacking_direction*y]}}
function startLabel(option){{return option.label+` (${{option.seconds_before_shot.toFixed(1)}} s before)`}}
function saveReview(){{const s=scenes[sceneIndex];reviews[key(s)]={{phase_review:q('.phase-review').value,start_review:q('.start-review').value,note:q('.review-note').value,viewed_start:windowSelect.value}};localStorage.setItem(storage,JSON.stringify(reviews));const done=Object.values(reviews).filter(r=>r.phase_review!=='unreviewed'&&r.start_review!=='unreviewed').length;q('.status').textContent=`Autosaved · ${{done}}/${{scenes.length}} done`}}
function rebuildFrames(){{const s=scenes[sceneIndex],option=s.start_options.find(o=>o.key===windowSelect.value)||s.start_options[0];visibleFrames=s.frames.filter(f=>f.frame_id>=option.frame_id);frameIndex=0;q('.slider').max=Math.max(0,visibleFrames.length-1);q('.slider').value=0;renderFrame()}}
function renderScene(){{const s=scenes[sceneIndex];sceneSelect.value=sceneIndex;q('.title').textContent=`${{s.match_label}} · ${{s.shooter_name}} shot`;q('.details').textContent=`open-play ${{s.build_up||'unknown'}} · xG ${{s.xg==null?'n/a':s.xg.toFixed(3)}} · up to ${{s.available_duration_seconds.toFixed(1)}} s backtracked`;windowSelect.innerHTML='';s.start_options.forEach(o=>{{const el=document.createElement('option');el.value=o.key;el.textContent=startLabel(o);windowSelect.appendChild(el)}});const r=reviews[key(s)]||{{phase_review:'unreviewed',start_review:'unreviewed',note:'',viewed_start:'attacking_half'}};windowSelect.value=s.start_options.some(o=>o.key===r.viewed_start)?r.viewed_start:'attacking_half';q('.phase-review').value=r.phase_review;q('.start-review').value=r.start_review;q('.review-note').value=r.note;q('.metrics').innerHTML=`Estimated possession length <strong>${{s.possession_duration_seconds.toFixed(1)}} s</strong><br>Last entry into the opponent half → shot <strong>${{s.attacking_half_duration_seconds.toFixed(1)}} s</strong><br>Share of possession with the ball in the opponent half <strong>${{(100*s.attacking_half_fraction).toFixed(0)}}%</strong><br>Shooting team's share of known control <strong>${{(100*s.attacking_team_control_fraction).toFixed(0)}}%</strong><br>Possession boundary <strong>${{s.boundary_reason}}</strong>`;rebuildFrames()}}
function renderFrame(){{if(!visibleFrames.length)return;const s=scenes[sceneIndex],f=visibleFrames[frameIndex],recent=visibleFrames.slice(Math.max(0,frameIndex-24),frameIndex+1).filter(x=>x.ball).map(x=>normalizedPoint(s,x.ball[0],x.ball[1]));q('.ball-trail').innerHTML=recent.length>1?`<polyline points="${{recent.map(p=>`${{px(p[0])}},${{py(p[1])}}`).join(' ')}}" fill="none" stroke="#5fe4ee" stroke-width=".45" opacity=".85"/>`:'';q('.objects').innerHTML=f.players.map(p=>{{const n=normalizedPoint(s,p[2],p[3]),attack=p[1]===s.shot_team_id,shooter=p[0]===s.shooter_id;return `<g><circle cx="${{px(n[0])}}" cy="${{py(n[1])}}" r="${{shooter?1.08:.72}}" fill="${{attack?'#ff6b55':'#438cff'}}" stroke="${{shooter?'#ffc84a':'white'}}" stroke-width="${{shooter?.5:.16}}"><title>${{p[4]}}</title></circle></g>`}}).join('')+(f.ball?(()=>{{const b=normalizedPoint(s,f.ball[0],f.ball[1]);return `<circle cx="${{px(b[0])}}" cy="${{py(b[1])}}" r=".43" fill="#111" stroke="white" stroke-width=".18"/>`}})():'');q('.slider').value=frameIndex;q('.time').textContent=`${{f.time_to_shot_s.toFixed(2)}} s before the shot · frame ${{f.frame_id}}`}}
q('.play').onclick=()=>{{playing=!playing;q('.play').textContent=playing?'❚❚ Pause':'▶ Play';if(playing)timer=setInterval(()=>{{frameIndex=frameIndex>=visibleFrames.length-1?0:frameIndex+1;renderFrame()}},100);else clearInterval(timer)}};q('.slider').oninput=()=>{{frameIndex=Number(q('.slider').value);renderFrame()}};q('.previous').onclick=()=>{{sceneIndex=(sceneIndex-1+scenes.length)%scenes.length;renderScene()}};q('.next').onclick=()=>{{sceneIndex=(sceneIndex+1)%scenes.length;renderScene()}};sceneSelect.onchange=()=>{{sceneIndex=Number(sceneSelect.value);renderScene()}};windowSelect.onchange=()=>{{saveReview();rebuildFrames()}};q('.phase-review').onchange=saveReview;q('.start-review').onchange=saveReview;q('.review-note').oninput=saveReview;
q('.export').onclick=()=>{{saveReview();const rows=[['match_id','shot_frame_id','event_id','phase_review','best_start','viewed_start','note']];scenes.forEach(s=>{{const r=reviews[key(s)]||{{phase_review:'unreviewed',start_review:'unreviewed',viewed_start:'',note:''}};rows.push([s.match_id,s.shot_frame_id,s.event_id,r.phase_review,r.start_review,r.viewed_start,r.note])}});const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n'),url=URL.createObjectURL(new Blob([csv],{{type:'text/csv'}})),a=document.createElement('a');a.href=url;a.download='shot_context_v0_1_reviews.csv';a.click();URL.revokeObjectURL(url)}};renderScene();
</script></body></html>"""
