"""Human-audit page for stable run onsets mined from shot contexts."""

from __future__ import annotations

import json
from typing import Sequence


def render_shot_context_onset_audit(scenes: Sequence[dict[str, object]]) -> str:
    data = json.dumps(list(scenes), ensure_ascii=False, separators=(",", ":")).replace(
        "</", "<\\/"
    )
    return f"""<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stable off-ball onset audit</title>
<style>:root{{--bg:#0b1422;--panel:#111e31;--line:#344965;--muted:#aebbd0;--text:#f4f7fc;--attack:#ff6b55;--defend:#438cff;--gold:#ffd04f;--cyan:#62e1ed}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}}main{{max-width:1500px;margin:auto;padding:23px}}h1{{margin:0 0 8px}}p{{color:var(--muted);line-height:1.5}}.note{{background:#18253a;border-left:4px solid var(--gold);padding:11px 14px;border-radius:5px}}.toolbar,.controls,.review{{display:flex;gap:10px;align-items:center;flex-wrap:wrap}}button,select,input{{font:inherit;color:var(--text);background:#17253b;border:1px solid #486080;border-radius:8px;padding:9px 11px}}button{{cursor:pointer}}.scene{{min-width:490px}}.layout{{display:grid;grid-template-columns:minmax(720px,1fr) 410px;gap:16px;margin-top:16px}}.panel{{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:15px}}svg.pitch{{width:100%;display:block;background:#17723a;border-radius:8px}}input[type=range]{{width:100%;padding:0}}.time{{margin-left:auto;font-variant-numeric:tabular-nums}}.metrics{{line-height:1.7;color:#c8d3e3}}.metrics strong{{color:#fff}}.review{{display:grid;align-items:start;margin-top:12px}}.review label{{display:grid;gap:5px;color:#cbd5e3}}.review input{{width:100%}}.status{{color:var(--cyan)}}.legend{{display:grid;grid-template-columns:auto 1fr;gap:7px 9px;color:#c6d2e2;margin:12px 0}}.dot{{width:13px;height:13px;border-radius:50%;margin-top:5px}}@media(max-width:1050px){{.layout{{grid-template-columns:1fr}}.scene{{min-width:280px;max-width:100%}}}}</style></head><body><main>
<h1>Shot-context 안의 안정 소유 오프더볼 onset · v0.1</h1><p class="note"><strong>지금은 2대1을 자동 판정한 결과가 아닙니다.</strong> 슈팅으로 끝난 공격 구간 안에서 기존 run-onset 조건과 추가 settled-possession gate를 모두 통과한 시점입니다. 안정 소유가 맞는지, 이후 2대1 후보로 발전시킬 관계가 보이는지만 확인합니다.</p>
<div class="toolbar"><button class="previous">← 이전</button><button class="next">다음 →</button><select class="scene"></select><button class="export">리뷰 CSV 저장</button><span class="status"></span></div><div class="layout"><section class="panel"><h2 class="title"></h2><p class="details"></p><svg class="pitch" viewBox="0 0 105 68"><rect width="105" height="68" fill="#17723a" stroke="white" stroke-width=".35"/><line x1="52.5" y1="0" x2="52.5" y2="68" stroke="white" stroke-width=".25"/><circle cx="52.5" cy="34" r="9.15" fill="none" stroke="white" stroke-width=".25"/><rect x="0" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><rect x="88.5" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><path d="M43 3 L61 3 M58 1 L61 3 L58 5" stroke="#ffd04f" stroke-width=".65" fill="none"/><text x="43" y="7" fill="#ffe49b" font-size="1.5">공격 방향</text><g class="runner-trail"></g><g class="objects"></g></svg><div class="controls"><button class="play">▶ 재생</button><span class="time"></span></div><input class="slider" type="range" min="0" value="0" step="1"></section><aside class="panel"><h3>검수 포인트</h3><div class="legend"><span class="dot" style="background:var(--gold)"></span><span>노란 링 = 검출된 오프더볼 runner</span><span class="dot" style="background:white"></span><span>흰 링 = t=0의 ball carrier</span><span class="dot" style="background:var(--attack)"></span><span>공격팀</span><span class="dot" style="background:var(--defend)"></span><span>수비팀</span></div><p class="metrics"></p><div class="review"><label>① t=0이 움직임 시작으로 맞는가?<select class="onset-review"><option value="unreviewed">미검수</option><option value="correct">정확</option><option value="too_early">너무 빠름</option><option value="too_late">너무 늦음</option><option value="not_onset">새 움직임이 아님</option><option value="unclear">애매함</option></select></label><label>② t=0은 안정 소유 상황인가?<select class="possession-review"><option value="unreviewed">미검수</option><option value="settled">안정 소유</option><option value="transition">전환 직후</option><option value="contested">경합/흐른 공</option><option value="restart">재개 상황</option><option value="unclear">애매함</option></select></label><label>③ 주변에 2대1로 볼 가능성이 있는가?<select class="interaction-review"><option value="unreviewed">미검수</option><option value="clear">분명히 보임</option><option value="possible">가능성 있음</option><option value="none">보이지 않음</option><option value="unclear">애매함</option></select></label><input class="review-note" placeholder="beneficiary·관련 수비수·경합 이유 등을 적어주세요"></div></aside></div></main>
<script id="payload" type="application/json">{data}</script><script>
const scenes=JSON.parse(document.getElementById('payload').textContent),q=s=>document.querySelector(s),storage='shot-context-onset-v0.1-reviews';let sceneIndex=0,frameIndex=0,playing=false,timer=null,reviews={{}};try{{reviews=JSON.parse(localStorage.getItem(storage)||'{{}}')}}catch(e){{}}
const key=s=>`${{s.match_id}}:${{s.onset_frame_id}}:${{s.runner_id}}`,px=x=>x+52.5,py=y=>34-y,select=q('.scene');scenes.forEach((s,i)=>{{const o=document.createElement('option');o.value=i;o.textContent=`${{i+1}}. ${{s.match_id.replace('DFL-MAT-','')}} · frame ${{s.onset_frame_id}} · ${{s.runner_name}} · shot +${{s.seconds_before_shot.toFixed(1)}}s`;select.appendChild(o)}});
function point(s,x,y){{return [s.attacking_direction*x,s.attacking_direction*y]}}function save(){{const s=scenes[sceneIndex];reviews[key(s)]={{onset:q('.onset-review').value,possession:q('.possession-review').value,interaction:q('.interaction-review').value,note:q('.review-note').value}};localStorage.setItem(storage,JSON.stringify(reviews));const done=Object.values(reviews).filter(r=>r.onset!=='unreviewed'&&r.possession!=='unreviewed'&&r.interaction!=='unreviewed').length;q('.status').textContent=`자동 저장 · ${{done}}/${{scenes.length}} 완료`}}
function renderScene(){{const s=scenes[sceneIndex];select.value=sceneIndex;q('.title').textContent=`${{s.match_label}} · runner ${{s.runner_name}}`;q('.details').textContent=`onset frame ${{s.onset_frame_id}} · 실제 슈팅까지 ${{s.seconds_before_shot.toFixed(1)}}초 · ${{s.onset_labels.join(' + ')}}`;q('.metrics').innerHTML=`onset speed <strong>${{s.onset_speed_mps.toFixed(2)}}m/s</strong><br>pre → post <strong>${{s.pre_speed_mps.toFixed(2)}} → ${{s.post_speed_mps.toFixed(2)}}m/s</strong><br>최근 1초 team control <strong>${{(100*s.settled_team_control_fraction).toFixed(0)}}%</strong><br>known control 중 같은 팀 <strong>${{(100*s.settled_same_team_known_fraction).toFixed(0)}}%</strong><br>공의 상대 진영 깊이 <strong>${{s.ball_progress_m.toFixed(1)}}m</strong><br>shot phase human label <strong>${{s.phase_human_review}}</strong>`;const r=reviews[key(s)]||{{onset:'unreviewed',possession:'unreviewed',interaction:'unreviewed',note:''}};q('.onset-review').value=r.onset;q('.possession-review').value=r.possession;q('.interaction-review').value=r.interaction;q('.review-note').value=r.note;frameIndex=0;q('.slider').max=s.frames.length-1;renderFrame()}}
function renderFrame(){{const s=scenes[sceneIndex],f=s.frames[frameIndex],trail=s.frames.slice(0,frameIndex+1).map(x=>x.players.find(p=>p[0]===s.runner_id)).filter(Boolean).map(p=>point(s,p[2],p[3]));q('.runner-trail').innerHTML=trail.length>1?`<polyline points="${{trail.map(p=>`${{px(p[0])}},${{py(p[1])}}`).join(' ')}}" fill="none" stroke="#ffd04f" stroke-width=".45"/>`:'';q('.objects').innerHTML=f.players.map(p=>{{const n=point(s,p[2],p[3]),attack=p[1]===s.team_id,runner=p[0]===s.runner_id,carrier=p[0]===s.carrier_id;return `<circle cx="${{px(n[0])}}" cy="${{py(n[1])}}" r="${{runner?1.12:.72}}" fill="${{attack?'#ff6b55':'#438cff'}}" stroke="${{runner?'#ffd04f':carrier?'white':'white'}}" stroke-width="${{runner?.52:carrier?.48:.16}}"><title>${{p[4]}}</title></circle>`}}).join('')+(f.ball?(()=>{{const b=point(s,f.ball[0],f.ball[1]);return `<circle cx="${{px(b[0])}}" cy="${{py(b[1])}}" r=".43" fill="#111" stroke="white" stroke-width=".18"/>`}})():'');q('.slider').value=frameIndex;q('.time').textContent=`t=${{f.relative_time_s>=0?'+':''}}${{f.relative_time_s.toFixed(2)}}초`}}
q('.play').onclick=()=>{{playing=!playing;q('.play').textContent=playing?'❚❚ 일시정지':'▶ 재생';if(playing)timer=setInterval(()=>{{frameIndex=frameIndex>=scenes[sceneIndex].frames.length-1?0:frameIndex+1;renderFrame()}},80);else clearInterval(timer)}};q('.slider').oninput=()=>{{frameIndex=Number(q('.slider').value);renderFrame()}};q('.previous').onclick=()=>{{sceneIndex=(sceneIndex-1+scenes.length)%scenes.length;renderScene()}};q('.next').onclick=()=>{{sceneIndex=(sceneIndex+1)%scenes.length;renderScene()}};select.onchange=()=>{{sceneIndex=Number(select.value);renderScene()}};q('.onset-review').onchange=save;q('.possession-review').onchange=save;q('.interaction-review').onchange=save;q('.review-note').oninput=save;
q('.export').onclick=()=>{{save();const rows=[['match_id','onset_frame_id','runner_id','onset_review','possession_review','interaction_review','note']];scenes.forEach(s=>{{const r=reviews[key(s)]||{{onset:'unreviewed',possession:'unreviewed',interaction:'unreviewed',note:''}};rows.push([s.match_id,s.onset_frame_id,s.runner_id,r.onset,r.possession,r.interaction,r.note])}});const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n'),url=URL.createObjectURL(new Blob([csv],{{type:'text/csv'}})),a=document.createElement('a');a.href=url;a.download='shot_context_onset_v0_1_reviews.csv';a.click();URL.revokeObjectURL(url)}};renderScene();
</script></body></html>"""
