#!/usr/bin/env python3
"""Render an interactive full-landscape direct--derived response audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from offball_value.bundesliga import find_bundesliga_files, load_bundesliga_match_metadata


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-json",
        type=Path,
        default=Path(
            "data/processed/direct_derived_response_map_v0_1/"
            "direct_derived_response_maps.json"
        ),
    )
    parser.add_argument(
        "--data-dir", type=Path, default=Path("data/raw/bundesliga-integrated")
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "data/processed/direct_derived_response_map_v0_1/"
            "direct_derived_response_map_audit.html"
        ),
    )
    return parser.parse_args()


TEMPLATE = r"""<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Direct–derived defender response map</title><style>
:root{--bg:#071321;--panel:#111f31;--panel2:#0d1928;--line:#304763;--text:#f4f7ff;--muted:#acbad0;--red:#ff6d5b;--blue:#438dff;--pink:#ff54c8;--cyan:#48e1d0;--violet:#c792ff;--gold:#ffd151;--green:#6ee7a8;--orange:#ff9658}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,Pretendard,system-ui,sans-serif}main{max-width:1680px;margin:auto;padding:22px}h1{margin:0 0 5px;font-size:1.9rem}h2,h3{margin:0 0 8px}p{color:var(--muted);line-height:1.45}.notice{border-left:4px solid var(--gold);background:#192a42;padding:10px 14px;border-radius:7px;margin:11px 0}.controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:9px 0}.controls .grow{flex:1}.controls label{color:#d9e4f4}select,button{font:inherit;color:var(--text);background:#1a2b43;border:1px solid #4a6483;border-radius:8px;padding:8px 11px}.layout{display:grid;grid-template-columns:minmax(800px,1fr) 540px;gap:16px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:14px}.pitch{display:block;width:100%;background:#17743a;border-radius:9px}.scrub{width:100%}.time{margin-left:auto;font-variant-numeric:tabular-nums}.legend{display:flex;gap:14px;flex-wrap:wrap;color:#cbd6e6;font-size:.82rem;margin-top:8px}.sw{display:inline-block;width:19px;border-top:4px solid;margin-right:5px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:9px 0}.card{padding:8px;background:#17273d;border:1px solid #354d69;border-radius:8px;cursor:pointer;min-height:67px}.card.active{border:2px solid var(--cyan);padding:7px}.card b{font-size:.84rem}.card small{display:block;color:var(--muted);margin-top:4px}.box{background:var(--panel2);border:1px solid #2d445f;border-radius:9px;padding:10px;margin-top:9px;line-height:1.45}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{background:#15263a;border-radius:8px;padding:9px}.metric strong{display:block;font-size:1.25rem;margin-top:3px}.endpoint-help{color:#c7d5e6;font-size:.86rem;margin:7px 0 0}.view-controls{display:flex;gap:7px;align-items:center;margin-bottom:9px}.view-controls button.active,.mode button.active{border-color:var(--gold);color:var(--gold);background:#2b2940}.landscape-controls.hidden{display:none}.scatter{width:100%;background:#0b1725;border-radius:8px;margin-top:8px}.candidate{display:grid;grid-template-columns:1fr 72px 72px;gap:6px;font-size:.82rem;padding:4px 0;border-bottom:1px solid #263c56}.candidate:last-child{border:0}.tag{display:inline-block;background:#243b58;color:#83e7ff;border-radius:99px;padding:4px 9px;font-weight:700}.warn{color:#ffd082}.good{color:var(--green)}.muted{color:var(--muted)}details summary{cursor:pointer;font-weight:700;color:#dce8f7}details[open] summary{margin-bottom:8px}@media(max-width:1180px){.layout{grid-template-columns:1fr}.cards{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main><h1>Direct–derived defender response map · v0.1</h1><p class="notice">먼저 <b>경로 보기</b>에서 실제 수비와 선택한 대응을 비교한다. 전체 후보가 필요할 때만 <b>전체 endpoint</b> 또는 오른쪽 scatter를 사용하면 된다.</p><div class="controls"><label>장면 <select class="scene"></select></label><button class="prev">← 이전</button><button class="next">다음 →</button><button class="play">▶ 재생</button><span class="time"></span><span class="grow"></span><span class="tag horizon"></span></div><div class="layout"><section class="panel"><div class="view-controls"><b>Pitch layer</b><button data-layer="paths" class="active">경로 보기</button><button data-layer="pareto">Pareto만</button><button data-layer="all">전체 endpoint</button></div><svg class="pitch" viewBox="0 0 105 68"><rect width="105" height="68" fill="#17743a" stroke="white" stroke-width=".3"/><line x1="52.5" x2="52.5" y1="0" y2="68" stroke="white" stroke-width=".25"/><circle cx="52.5" cy="34" r="9.15" fill="none" stroke="white" stroke-width=".25"/><rect x="0" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><rect x="88.5" y="13.84" width="16.5" height="40.32" fill="none" stroke="white" stroke-width=".25"/><g class="endpoints"></g><g class="paths"></g><g class="moving"></g></svg><input class="scrub" type="range" min="0" value="0"><div class="legend"><span><i class="sw" style="border-color:var(--pink)"></i>runner 실제</span><span><i class="sw" style="border-color:var(--cyan)"></i>선택한 가상 수비</span><span><i class="sw" style="border-color:white;border-top-style:dashed"></i>실제 수비</span><span><i class="sw" style="border-color:var(--violet)"></i>derived beneficiary</span></div><div class="controls mode landscape-controls hidden"><span>색상</span><button data-mode="direct" class="active">Runner</button><button data-mode="derived">파생</button><button data-mode="regret">Regret</button></div><p class="endpoint-help layer-help">실제 궤적은 흰 점선, 선택한 가상 대응은 청록색이다. 흰 X는 실제 도착 위치다.</p></section><aside class="panel"><h2 class="title"></h2><p class="subtitle"></p><div class="cards"></div><div class="metrics"><div class="metric">Runner direct<strong class="direct"></strong><span class="muted">residual influence</span></div><div class="metric">Team derived<strong class="derived"></strong><span class="muted">runner 제외 최대</span></div></div><div class="box selected"></div><svg class="scatter" viewBox="0 0 500 270"></svg><div class="box tradeoff"></div><details class="box"><summary>Relevant defender 후보 보기</summary><div class="candidates"></div></details><details class="box"><summary>기존 사람 검수 보기</summary><div class="review-note"></div></details></aside></div></main><script id="data" type="application/json">__DATA__</script><script>
const DATA=JSON.parse(document.getElementById('data').textContent);let sceneIndex=0,selected='compromise',customIndex=null,colorMode='direct',pitchLayer='paths',frameIndex=0,playing=false,timer=null;const $=s=>document.querySelector(s),S=()=>DATA.scenes[sceneIndex],dirX=x=>52.5+S().attacking_direction*x,py=y=>34-y,fmt=v=>(100*v).toFixed(1)+'%';
const lerp=(a,b,t)=>a+(b-a)*t,hex=(a,b,t)=>{let p=x=>parseInt(x,16),A=[p(a.slice(1,3)),p(a.slice(3,5)),p(a.slice(5,7))],B=[p(b.slice(1,3)),p(b.slice(3,5)),p(b.slice(5,7))];return'#'+A.map((v,i)=>Math.round(lerp(v,B[i],t)).toString(16).padStart(2,'0')).join('')};
function pathInterp(times,xy,t){if(t<=times[0])return xy[0];if(t>=times.at(-1))return xy.at(-1);for(let i=1;i<times.length;i++)if(t<=times[i]){let q=(t-times[i-1])/(times[i]-times[i-1]);return[lerp(xy[i-1][0],xy[i][0],q),lerp(xy[i-1][1],xy[i][1],q)]}}
function actualDefenderAt(t){let p=S().actual_response.path_txy;if(t<=p[0][0])return p[0].slice(1);if(t>=p.at(-1)[0])return p.at(-1).slice(1);for(let i=1;i<p.length;i++)if(t<=p[i][0]){let q=(t-p[i-1][0])/(p[i][0]-p[i-1][0]);return[lerp(p[i-1][1],p[i][1],q),lerp(p[i-1][2],p[i][2],q)]}}
function selectedResponse(){if(selected==='actual')return null;if(selected==='custom')return S().responses[customIndex];return S().responses[S().named_response_indices[selected]]}
function selectedStats(){let r=selectedResponse();return r||S().actual_response}
function playerFromFrame(frame,id){let p=frame.players.find(x=>x[0]===id);return p?[p[2],p[3]]:null}
function actualPath(id,start=0){return S().background_frames.filter(f=>f.time_s>=start).map(f=>[f.time_s,...playerFromFrame(f,id)])}
function poly(points,color,dash='',width=.45,opacity=1){return`<polyline points="${points.map(p=>`${dirX(p[1])},${py(p[2])}`).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}" stroke-dasharray="${dash}" opacity="${opacity}"/>`}
function colorFor(response){let vals=S().responses.map(r=>colorMode==='direct'?r.direct_threat:colorMode==='derived'?r.derived_threat:r.normalized_compromise_regret),lo=Math.min(...vals),hi=Math.max(...vals),v=colorMode==='direct'?response.direct_threat:colorMode==='derived'?response.derived_threat:response.normalized_compromise_regret,t=(v-lo)/Math.max(hi-lo,1e-9);return colorMode==='derived'?hex('#55dfc5','#d56cff',t):hex('#62e59a','#ff6657',t)}
function drawEndpoints(){let s=S(),r=selectedResponse(),pool=pitchLayer==='all'?s.responses:pitchLayer==='pareto'?s.responses.filter(x=>x.pareto):[];$('.endpoints').innerHTML=pool.map(x=>`<circle class="endpoint" data-i="${x.index}" cx="${dirX(x.endpoint_x)}" cy="${py(x.endpoint_y)}" r="${x.pareto?.31:.2}" fill="${colorFor(x)}" fill-opacity="${x.pareto?.72:.42}" stroke="${x.pareto?'#ffd151':'none'}" stroke-width=".14"/>`).join('')+`<path d="M${dirX(s.actual_response.endpoint_x)-.55},${py(s.actual_response.endpoint_y)-.55}l1.1,1.1m0,-1.1l-1.1,1.1" stroke="white" stroke-width=".25"/><circle cx="${r?dirX(r.endpoint_x):-100}" cy="${r?py(r.endpoint_y):-100}" r=".65" fill="none" stroke="#48e1d0" stroke-width=".25"/>`;document.querySelectorAll('.endpoint').forEach(e=>e.onclick=()=>chooseCustom(Number(e.dataset.i)));$('.landscape-controls').classList.toggle('hidden',pitchLayer==='paths');$('.layer-help').textContent=pitchLayer==='paths'?'실제 궤적은 흰 점선, 선택한 가상 대응은 청록색이다. 흰 X는 실제 도착 위치다.':pitchLayer==='pareto'?'금색 테두리의 Pareto endpoint만 표시했다. 점을 누르면 해당 수비 궤적이 열린다.':'모든 고유 1m endpoint를 표시했다. 점을 누르면 해당 수비 궤적이 열린다.'}
function drawPaths(){let s=S(),r=selectedResponse(),beneficiary=selectedStats().beneficiary_id,html=poly(actualPath(s.runner_id),'#ff54c8','',.58)+poly(s.actual_response.path_txy,'white','1 .55',.42,.92);if(beneficiary&&beneficiary!==s.runner_id)html+=poly(actualPath(beneficiary),'#c792ff','1 .55',.38,.8);if(r)html+=poly(r.times_s.map((t,i)=>[t,...r.path_xy[i]]),'#48e1d0','',.62);$('.paths').innerHTML=html}
function drawFrame(){let s=S(),frame=s.background_frames[frameIndex],t=frame.time_s,r=selectedResponse(),actual=t<0?playerFromFrame(frame,s.defender_id):actualDefenderAt(t),counter=r?(t<0?actual:pathInterp(r.times_s,r.path_xy,t)):actual,beneficiary=selectedStats().beneficiary_id;let html=frame.players.filter(p=>![s.runner_id,s.defender_id,beneficiary].includes(p[0])).map(p=>`<circle cx="${dirX(p[2])}" cy="${py(p[3])}" r=".68" fill="${p[1]===s.attacking_team_id?'#ff6d5b':'#438dff'}" stroke="white" stroke-width=".13"><title>${DATA.names[p[0]]||p[0]}</title></circle>`).join('');if(frame.ball)html+=`<circle cx="${dirX(frame.ball[0])}" cy="${py(frame.ball[1])}" r=".4" fill="#111" stroke="white" stroke-width=".14"/>`;let runner=playerFromFrame(frame,s.runner_id);html+=`<circle cx="${dirX(runner[0])}" cy="${py(runner[1])}" r="1.05" fill="#ff54c8" stroke="white" stroke-width=".22"><title>${s.runner_name}</title></circle>`;if(beneficiary&&beneficiary!==s.runner_id){let b=playerFromFrame(frame,beneficiary);if(b)html+=`<circle cx="${dirX(b[0])}" cy="${py(b[1])}" r=".95" fill="#ff6d5b" stroke="#c792ff" stroke-width=".45"><title>${DATA.names[beneficiary]||beneficiary}</title></circle>`}html+=`<circle cx="${dirX(actual[0])}" cy="${py(actual[1])}" r="1.18" fill="none" stroke="white" stroke-width=".3"><title>실제 ${s.defender_name}</title></circle>`;if(r)html+=`<circle cx="${dirX(counter[0])}" cy="${py(counter[1])}" r=".9" fill="#438dff" stroke="#48e1d0" stroke-width=".42"><title>가상 ${s.defender_name}</title></circle>`;else html+=`<circle cx="${dirX(actual[0])}" cy="${py(actual[1])}" r=".82" fill="#438dff" stroke="#48e1d0" stroke-width=".2"/>`;$('.moving').innerHTML=html;$('.scrub').value=frameIndex;$('.time').textContent=`t=${t>=0?'+':''}${t.toFixed(2)}초`}
const labels={actual:'실제 수비',direct_minimum:'Runner 최소',derived_minimum:'파생 최소',compromise:'Compromise',joint_sum_minimum:'합계 최소',nearest_actual_endpoint:'실제 endpoint 근접'};
function cards(){let s=S();$('.cards').innerHTML=Object.entries(labels).map(([k,label])=>{let stat=k==='actual'?s.actual_response:s.responses[s.named_response_indices[k]],active=selected===k;return`<div class="card ${active?'active':''}" data-key="${k}"><b>${label}</b><small>R ${fmt(stat.direct_threat)} · D ${fmt(stat.derived_threat)}</small></div>`}).join('')+(selected==='custom'?`<div class="card active" data-key="custom"><b>직접 선택 #${customIndex}</b><small>endpoint cloud/scatter</small></div>`:'');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>{let k=c.dataset.key;if(k!=='custom')chooseNamed(k)})}
function chooseNamed(k){selected=k;customIndex=null;cards();drawEndpoints();drawPaths();drawFrame();details();drawScatter()}
function chooseCustom(i){selected='custom';customIndex=i;cards();drawEndpoints();drawPaths();drawFrame();details();drawScatter()}
function details(){let s=S(),r=selectedStats(),name=DATA.names[r.beneficiary_id]||r.beneficiary_id;$('.direct').textContent=fmt(r.direct_threat);$('.derived').textContent=fmt(r.derived_threat);$('.selected').innerHTML=`<b>${selected==='actual'?'실제 수비 궤적':selected==='custom'?`직접 선택 endpoint #${customIndex}`:labels[selected]}</b><br>파생 위협의 대표 beneficiary: <b>${name}</b>${r.pareto?'<br><span class="good">Pareto response</span>':''}${selected==='actual'?'<br><span class="warn">실제 궤적은 생성 후보가 아니며 별도로 평가했다.</span>':`<br>endpoint (${r.endpoint_x.toFixed(1)}, ${r.endpoint_y.toFixed(1)}) · regret ${(100*r.normalized_compromise_regret).toFixed(1)}%`}`}
function drawScatter(){let s=S(),all=s.responses,actual=s.actual_response,w=500,h=270,pad=40,xv=all.map(r=>r.direct_threat).concat(actual.direct_threat),yv=all.map(r=>r.derived_threat).concat(actual.derived_threat),xmin=Math.min(...xv),xmax=Math.max(...xv),ymin=Math.min(...yv),ymax=Math.max(...yv),sx=x=>pad+(x-xmin)/Math.max(xmax-xmin,1e-9)*(w-2*pad),sy=y=>h-pad-(y-ymin)/Math.max(ymax-ymin,1e-9)*(h-2*pad),r=selectedResponse();let html=`<rect width="${w}" height="${h}" fill="#0b1725"/><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" stroke="#71859e"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}" stroke="#71859e"/><text x="${w/2}" y="${h-7}" text-anchor="middle" fill="#aebdd0" font-size="11">Runner direct →</text><text x="12" y="${h/2}" transform="rotate(-90 12 ${h/2})" text-anchor="middle" fill="#aebdd0" font-size="11">Team derived →</text>`;html+=all.map(x=>`<circle class="scatter-point" data-i="${x.index}" cx="${sx(x.direct_threat)}" cy="${sy(x.derived_threat)}" r="${x.pareto?3.5:2.2}" fill="${colorFor(x)}" fill-opacity=".78" stroke="${x.pareto?'#ffd151':'none'}" stroke-width="1.2"/>`).join('');html+=`<path d="M${sx(actual.direct_threat)-5},${sy(actual.derived_threat)-5}l10,10m0,-10l-10,10" stroke="white" stroke-width="1.8"/>`;if(r)html+=`<circle cx="${sx(r.direct_threat)}" cy="${sy(r.derived_threat)}" r="6" fill="none" stroke="#48e1d0" stroke-width="2"/>`;$('.scatter').innerHTML=html;document.querySelectorAll('.scatter-point').forEach(e=>e.onclick=()=>chooseCustom(Number(e.dataset.i)))}
function sceneInfo(){let s=S(),reason={shot:'실제 슈팅 직전',diagnostic_cap:'진단 상한',runner_reception:'runner 볼 수령',opponent_control:'상대 소유 전환',ball_outside_pitch:'볼 아웃'}[s.horizon_reason]||s.horizon_reason;$('.title').textContent=`${s.runner_name} · defender ${s.defender_name}`;$('.subtitle').innerHTML=`${s.match_label} · frame ${s.onset_frame_id}<br><b>${s.evaluated_endpoint_count}</b>개 고유 feasible endpoint · <b>${s.pareto_response_count}</b>개 Pareto · 실제 슈팅까지 ${s.seconds_to_shot.toFixed(2)}초`;$('.horizon').textContent=`평가 H=${s.horizon_seconds.toFixed(1)}초 · ${reason}`;let d=s.tradeoff;$('.tradeoff').innerHTML=`<h3>Cross-cost</h3>파생 기회를 우선하면 Runner 위협 <b style="color:var(--orange)">+${(100*d.direct_branch_gap).toFixed(1)}%p</b><br>Runner를 우선하면 파생 위협 <b style="color:var(--violet)">+${(100*d.beneficiary_branch_gap).toFixed(1)}%p</b><br>최소 branch gap <b>${(100*d.minimum_branch_gap).toFixed(1)}%p</b> · compromise regret <b>${(100*d.normalized_compromise_regret).toFixed(1)}%</b><br><span class="warn">residual influence 비율이지 득점확률이 아니다.</span>`;$('.candidates').innerHTML=s.candidate_defenders.slice(0,5).map((x,i)=>`<div class="candidate"><b>${i+1}. ${x.defender_name}${x.defender_id===s.defender_id?' ✓':''}</b><span>R ${(100*x.direct_responsibility).toFixed(1)}%p</span><span>D ${(100*x.derived_responsibility).toFixed(1)}%p</span></div>`).join('');$('.review-note').innerHTML=`<h3>기존 사람 검수</h3>onset <b>${s.review.onset}</b> · possession <b>${s.review.possession}</b> · interaction <b>${s.review.interaction}</b>${s.review.note?`<p>${s.review.note}</p>`:''}`}
function setScene(i){sceneIndex=(Number(i)+DATA.scenes.length)%DATA.scenes.length;$('.scene').value=sceneIndex;selected='compromise';customIndex=null;frameIndex=0;$('.scrub').max=S().background_frames.length-1;sceneInfo();cards();drawEndpoints();drawPaths();drawFrame();details();drawScatter()}
function init(){let sel=$('.scene');sel.innerHTML=DATA.scenes.map((s,i)=>`<option value="${i}">${i+1}. ${s.runner_name} · frame ${s.onset_frame_id} · ${s.review.interaction}</option>`).join('');sel.onchange=e=>setScene(e.target.value);$('.prev').onclick=()=>setScene(sceneIndex-1);$('.next').onclick=()=>setScene(sceneIndex+1);$('.scrub').oninput=e=>{frameIndex=Number(e.target.value);drawFrame()};$('.play').onclick=e=>{playing=!playing;e.target.textContent=playing?'❚❚ 일시정지':'▶ 재생';if(playing)timer=setInterval(()=>{frameIndex=frameIndex>=S().background_frames.length-1?0:frameIndex+1;drawFrame()},70);else clearInterval(timer)};document.querySelectorAll('.view-controls button').forEach(b=>b.onclick=()=>{pitchLayer=b.dataset.layer;document.querySelectorAll('.view-controls button').forEach(x=>x.classList.toggle('active',x===b));drawEndpoints()});document.querySelectorAll('.mode button').forEach(b=>b.onclick=()=>{colorMode=b.dataset.mode;document.querySelectorAll('.mode button').forEach(x=>x.classList.toggle('active',x===b));drawEndpoints();drawScatter()});setScene(0)}init();
</script></body></html>"""


def main() -> None:
    args = parse_args()
    scenes = json.loads(args.input_json.read_text(encoding="utf-8"))
    names = {}
    for match_id in sorted({scene["match_id"] for scene in scenes}):
        metadata = load_bundesliga_match_metadata(
            find_bundesliga_files(args.data_dir, match_id)["matchinfo"]
        )
        names.update(
            {
                player_id: player.short_name
                for player_id, player in metadata.players.items()
            }
        )
    payload = json.dumps(
        {"scenes": scenes, "names": names},
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(TEMPLATE.replace("__DATA__", payload), encoding="utf-8")
    print(f"audit: {args.output.resolve()}")


if __name__ == "__main__":
    main()
